server:
  port: 8081

spring:
  cloud:
    gateway:
      routes:
        - id: employee-service
          uri: lb://EMPLOYEE-SERVICE
          predicates:
            - Path=/api/employees/**
        - id: department-service
          uri: lb://DEPARTMENT-SERVICE
          predicates:
            - Path=/api/departments/**
        - id: salary-service
          uri: lb://SALARY-SERVICE
          predicates:
            - Path=/salary/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
