server:
  port: 8088

spring:
  application:
    name: salary-service

  datasource:
    url:  jdbc:oracle:thin:@localhost:1521/FREEPDB1

    username: system
    password: root
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  database-platform: org.hibernate.dialect.OracleDialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
